### ISSUE TITLE
Search not working proper at https://docs.sodafoundation.io/

### ISSUE THREAD

**Issue by skdwriting** [sodafoundation/documentation#257] opened 2022-04-22 11:30 UTC
**Issue/Feature Description:**
Currently the search button shows only the current page search results highlighted. Not search in side the document pages.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
To get proper search results and find relevant documents faster

**How to reproduce, in case of a bug:**
Got to https://docs.sodafoundation.io/ and left side search button enter any keyword to search.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
NA

**Comment by anvithks** [comment] 2022-04-23 03:43
This is a duplicate of #108 which was seemingly fixed in #136 .

The issue was also raised in the Learn theme demo [here](https://github.com/matcornic/hugo-theme-learn/issues/438)
We use the Learn theme for the documentation website.

Looks like the change made in the baseUrl has not fixed the issue, probably because we redirect the netlify generated website from `https://soda-docs.netlify.app/` to `https://docs.sodafoundation.io`.

![soda_documentation_search_error](https://user-images.githubusercontent.com/19162717/164873882-474644ba-6e04-4f87-af49-b0f44c807d88.png)


**Probable fix:** Changing the baseUrl to `https://docs.sodafoundation.io` in the confid.toml file may fix the issue. We will need to test this before merging though.

**Closed** 2022-04-28 05:28 UTC
Labels: SODACODE2022, SODAHIGH
